<?php if (! $this->compact): ?>
<div class="controls">
<?= $this->tabs ?>
</div>
<?php endif ?>
<div class="content">
<h1>Controllers</h1>


<?php if (empty($this->ntpstatsng_controllers)): ?>
<?= $this->translate('No controller found') ?>
</div>
<?php return; endif ?>
<table class="action">
    <thead>
        <tr>
            <th>Controller name</th>
            <th>Display name</th>
            <th>Address</th>
        </tr>
    </thead>
    <tbody>
<?php foreach ($this->ntpstatsng_controllers as $row): ?>
        <tr>
            <td><?= $this->qlink($row->object_name, 'ntpstatsng/list/controllers', array('id' => $row->id)) ?></td>
            <td><?= $row->display_name ?></td>
            <td><?= $row->address ?></td>
        </tr>
<?php endforeach ?>
    </tbody>
</table>
</div>
