<?php if (! $this->compact): ?>
<div class="controls">
<?= $this->tabs ?>
</div>
<?php endif ?>

<div class="content" data-base-target="_next">
<h1><?= $this->title ?></h1>

<?php if (empty($this->ntpstatsng_probes)): ?>
<?= $this->translate('No probe found') ?>
</div>
<?php return; endif ?>

<table class="action">
    <thead>
        <tr>
            <th>Probe name</th>
            <th>Address</th>
        </tr>
    </thead>
    <tbody>
<?php foreach ($this->ntpstatsng_probes as $row): ?>
        <tr>
            <td><?= $this->qlink($row->object_name, 'ntpstatsng/modify/probe', array('name' => $row->object_name)) ?></td>
            <td><?= $row->address ?></td>
        </tr>
<?php endforeach ?>
    </tbody>
</table>
</div>
