<?php if (! $this->compact): ?>
<div class="controls">
<?= $this->tabs ?>
</div>
<?php endif ?>
<div class="content">
<h1>Zones</h1>


<?php if (empty($this->ntpstatsng_zones)): ?>
<?= $this->translate('No zone found') ?>
</div>
<?php return; endif ?>
<table class="action">
    <thead>
        <tr>
            <th>Zone name</th>
            <th>Display name</th>
        </tr>
    </thead>
    <tbody>
<?php foreach ($this->ntpstatsng_zones as $row): ?>
        <tr>
            <td><?= $this->qlink($row->object_name, 'ntpstatsng/list/zones', array('id' => $row->id)) ?></td>
            <td><?= $row->display_name ?></td>
        </tr>
<?php endforeach ?>
    </tbody>
</table>
</div>
